projects:
  coffeematchingapp:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: lib/API.ts
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
